// Generated by BUCKLESCRIPT VERSION 4.0.17, PLEASE EDIT WITH CARE
'use strict';

var Caml_module = require("bs-platform/lib/js/caml_module.js");

var Euler = Caml_module.init_mod([
      "Three.ml",
      18,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], Euler, Euler);

var Matrix3 = Caml_module.init_mod([
      "Three.ml",
      30,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], Matrix3, Matrix3);

var Vector2 = Caml_module.init_mod([
      "Three.ml",
      92,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], Vector2, Vector2);

var Vector3 = Caml_module.init_mod([
      "Three.ml",
      171,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], Vector3, Vector3);

var Color = Caml_module.init_mod([
      "Three.ml",
      186,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], Color, Color);

var Object3D = Caml_module.init_mod([
      "Three.ml",
      241,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], Object3D, Object3D);

var Group = Caml_module.init_mod([
      "Three.ml",
      251,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], Group, Group);

var Camera = Caml_module.init_mod([
      "Three.ml",
      271,
      6
    ], [[[[0]]]]);

Caml_module.update_mod([[[[0]]]], Camera, Camera);

var Texture = Caml_module.init_mod([
      "Three.ml",
      283,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], Texture, Texture);

var VideoTexture = Caml_module.init_mod([
      "Three.ml",
      294,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], VideoTexture, VideoTexture);

var TextureLoader = Caml_module.init_mod([
      "Three.ml",
      305,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], TextureLoader, TextureLoader);

var SVGLoader = Caml_module.init_mod([
      "Three.ml",
      316,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], SVGLoader, SVGLoader);

var Float32Array = Caml_module.init_mod([
      "Three.ml",
      325,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], Float32Array, Float32Array);

var Geometry = Caml_module.init_mod([
      "Three.ml",
      416,
      6
    ], [[
        0,
        [[0]],
        [[0]],
        [[0]],
        [[0]],
        [[
            [[0]],
            [[0]],
            [[0]],
            0
          ]]
      ]]);

Caml_module.update_mod([[
        0,
        [[0]],
        [[0]],
        [[0]],
        [[0]],
        [[
            [[0]],
            [[0]],
            [[0]],
            0
          ]]
      ]], Geometry, Geometry);

var Material = Caml_module.init_mod([
      "Three.ml",
      468,
      6
    ], [[
        [[
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]],
        [[
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]],
        [[
            0,
            0,
            0,
            0,
            0,
            0
          ]],
        [[
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]]
      ]]);

Caml_module.update_mod([[
        [[
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]],
        [[
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]],
        [[
            0,
            0,
            0,
            0,
            0,
            0
          ]],
        [[
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]]
      ]], Material, Material);

var Line = Caml_module.init_mod([
      "Three.ml",
      483,
      6
    ], [[
        [[0]],
        0
      ]]);

Caml_module.update_mod([[
        [[0]],
        0
      ]], Line, Line);

var Mesh = Caml_module.init_mod([
      "Three.ml",
      499,
      6
    ], [[
        0,
        0
      ]]);

Caml_module.update_mod([[
        0,
        0
      ]], Mesh, Mesh);

var Scene = Caml_module.init_mod([
      "Three.ml",
      518,
      6
    ], [[
        0,
        0
      ]]);

Caml_module.update_mod([[
        0,
        0
      ]], Scene, Scene);

var WebGLRenderer = Caml_module.init_mod([
      "Three.ml",
      559,
      6
    ], [[
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]]);

Caml_module.update_mod([[
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]], WebGLRenderer, WebGLRenderer);

var OrbitControls = Caml_module.init_mod([
      "Three.ml",
      577,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], OrbitControls, OrbitControls);

var WebVRPolyfill = Caml_module.init_mod([
      "Three.ml",
      588,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], WebVRPolyfill, WebVRPolyfill);

var StereoEffect = Caml_module.init_mod([
      "Three.ml",
      600,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], StereoEffect, StereoEffect);

var Light = Caml_module.init_mod([
      "Three.ml",
      613,
      6
    ], [[[[0]]]]);

Caml_module.update_mod([[[[0]]]], Light, Light);

var GLTFExporter = Caml_module.init_mod([
      "Three.ml",
      623,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], GLTFExporter, GLTFExporter);

exports.Euler = Euler;
exports.Matrix3 = Matrix3;
exports.Vector2 = Vector2;
exports.Vector3 = Vector3;
exports.Color = Color;
exports.Object3D = Object3D;
exports.Group = Group;
exports.Camera = Camera;
exports.Texture = Texture;
exports.VideoTexture = VideoTexture;
exports.TextureLoader = TextureLoader;
exports.SVGLoader = SVGLoader;
exports.Float32Array = Float32Array;
exports.Geometry = Geometry;
exports.Material = Material;
exports.Line = Line;
exports.Mesh = Mesh;
exports.Scene = Scene;
exports.WebGLRenderer = WebGLRenderer;
exports.OrbitControls = OrbitControls;
exports.WebVRPolyfill = WebVRPolyfill;
exports.StereoEffect = StereoEffect;
exports.Light = Light;
exports.GLTFExporter = GLTFExporter;
/* Euler Not a pure module */
