// Generated by BUCKLESCRIPT VERSION 4.0.18, PLEASE EDIT WITH CARE
'use strict';

var Caml_module = require("bs-platform/lib/js/caml_module.js");

var $$Math = Caml_module.init_mod([
      "Three.ml",
      15,
      6
    ], [[[[0]]]]);

Caml_module.update_mod([[[[0]]]], $$Math, $$Math);

var Vector3 = Caml_module.init_mod([
      "Three.ml",
      26,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], Vector3, Vector3);

var Camera = Caml_module.init_mod([
      "Three.ml",
      38,
      6
    ], [[[[0]]]]);

Caml_module.update_mod([[[[0]]]], Camera, Camera);

var Geometry = Caml_module.init_mod([
      "Three.ml",
      47,
      6
    ], [[[[0]]]]);

Caml_module.update_mod([[[[0]]]], Geometry, Geometry);

var Material = Caml_module.init_mod([
      "Three.ml",
      57,
      6
    ], [[[[0]]]]);

Caml_module.update_mod([[[[0]]]], Material, Material);

var Mesh = Caml_module.init_mod([
      "Three.ml",
      67,
      6
    ], [[
        0,
        0
      ]]);

Caml_module.update_mod([[
        0,
        0
      ]], Mesh, Mesh);

var Scene = Caml_module.init_mod([
      "Three.ml",
      77,
      6
    ], [[
        0,
        0
      ]]);

Caml_module.update_mod([[
        0,
        0
      ]], Scene, Scene);

var WebGLRenderer = Caml_module.init_mod([
      "Three.ml",
      88,
      6
    ], [[0]]);

Caml_module.update_mod([[0]], WebGLRenderer, WebGLRenderer);

exports.$$Math = $$Math;
exports.Vector3 = Vector3;
exports.Camera = Camera;
exports.Geometry = Geometry;
exports.Material = Material;
exports.Mesh = Mesh;
exports.Scene = Scene;
exports.WebGLRenderer = WebGLRenderer;
/* Math Not a pure module */
